name: debug-wheel-build

on:
  push:
    branches:
      - 'debug/**'

jobs:
  build-manylinux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        pip install coverage pytest pytest-cov -U
        pip install Cython --install-option="--no-cython-compile"
        pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib -U
        pip install -r test-requirements.txt
        pip install -e .
        python setup.py build sdist
    - name: Test with pytest
      run: |
        make test
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2010_x86_64
      with:
        build-requirements: 'cython'
        python-versions: "cp38-cp38 cp39-cp39 cp310-cp310"
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/*.whl